customer/urls.py
from django.urls import path
from .views import CustomerlistView, CustomerCreateView
app_name = "customer"

urlpatterns = [
    path('list/', CustomerlistView.as_view(), name="customer-list"),
    path('', CustomerCreateView.as_view(), name="customer-create"),
]

sistemas_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html"), name="index"),
    path("customer/", include("customer.urls"))
]

core/models.py
from django.db import models

# Create your models here.

customer/models.py
from django.db import models


class Customer(models.Model):
    first_name = models.CharField(max_length=30, default="")
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    birth_date = models.DateField()
    area_code = models.CharField(max_length=3)
    phone_number = models.CharField(max_length=9)
    contry = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    created_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateField(auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_full_phone_number(self):
        return f"({self.area_code}) {self.phone_number}"

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_full_city(self):
        return f"{self.city} - {self.state}"

    class Meta:
        db_table = "customer"

customer/forms.py
from django import forms
from .models import Customer


class DateInput(forms.DateInput):
    input_type = "date"


class CustomerForm(forms.ModelForm):
    first_name = forms.CharField(
        label="Nome",
        error_messages={'max_lenght': "Não pode ter mais de 30 caracteres"}
    )
    last_name = forms.CharField(
        label="Sobrenome",
        error_messages={'max_lenght': "Não pode ter mais de 30 caracteres"}
    )
    email = forms.EmailField(label="E-mail")
    birth_date = forms.DateField(label="Data de nascimento", widget=DateInput())

    area_code = forms.RegexField(
        label="DDD",
        regex=r"^\+?1?[0-9]{2}$",
        error_messages={'invalid': "Número de dd inválido"}
    )
    phone_number = forms.RegexField(
        label="Telefone",
        regex=r"^\+?1?[0-9]{9,15}$",
        error_messages={'invalid': "Número de Telefone inválido"}
    )
    country = forms.CharField(label="País")
    state = forms.CharField(label="Estado")
    city = forms.CharField(label="Cidade")

    class Meta:
        model = Customer
        fields = (
            "first_name",
            "last_name",
            "email",
            "birth_date",
            "area_code",
            "phone_number",
            "contry",
            "state",
            "city"
        )

core/views.py
from django.shortcuts import render

# Create your views here.

customer/views.py
from django.shortcuts import render
# Create your views here.
from django.views.generic import ListView, CreateView
from .models import Customer
from .forms import CustomerForm
from django.urls import reverse


class CustomerlistView(ListView):
    template_name = "customer/customer_list.html"
    model = Customer
    queryset = Customer.objects.all()


class CustomerCreateView(CreateView):
    template_name = "customer/customer.html"
    form_class = CustomerForm

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("customer:customer-list")

core/templates/index.html
{% extends "model_page.html" %}

{% block content %}
    <h1>CRM</h1>
 {% endblock %}

core/templates/model_footer.html
<div class="container text-center">
    <small>Desenvolvido por Filipe André</small>
</div>

core/templates/model_header.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <a class="navbar-brand" href={% url 'index' %}>CRM</a>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        </li>
        <a class="nav-link" href="{% url 'customer:customer-list' %}">Clientes</a>
    </ul>
</nav>

core/templates/model_page.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
</head>
<body class="d-flex flex-column">
<header>
    {%  include "model_header.html" %}
</header>
<main class="content" style="margin-top: 5%">
<div class="container">
    {% block content %}{% endblock %}
</div>
</main>

<footer class="py-4 bg-dark text-white-50">
    {% include "model_footer.html" %}
</footer>
</body>
<style>
    html, body {
        height: 100%;
    }
    main{
        flex: 1 0 auto;
    }
    footer{
        flex-shrink:initial;
        margin-top: 2em;

    }
</style>
</html>

customer/templates/customer/customer.html
{% extends "model_page.html" %}
{%load crispy_forms_tags %}
{% block content %}
    {% if form.erros %}
        {% for field in form %}
            {% for error in field.errors %}
            <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
            </div>
            {% endfor %}
        {% endfor %}
    {% endif %}

    <form method="POST">{% csrf_token %}
     {{form|crispy}}
    <button type="submit" class="btn btn-primary">Salvar</button>
    </form>

{% endblock %}

customer/templates/customer/customer_list.html
{% extends "model_page.html" %}

{% block content %}
<h2>Clientes</h2>
    <a href="{% url 'customer:customer-create' %}">
    <button type="button" class="btn btn-success" style="float: right; margin-bottom: 5px">Adicionar</button>
    </a>
    <table class="table table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
        <th>Cidade</th>
        <th>Telefone</th>
        <th>Email</th>
        <th></th>
    </tr>
  </thead>

  <tbody>
  {% for customer in customer_list %}
    <tr>
        <td><a href="#">{{ customer.get_full_name}}</a></td>
        <td>{{ customer.get_full_city}}</td>
        <td>{{ customer.get_full_phone_number}}</td>
        <td>{{ customer.email }}</td>
        <td><button type="button" class="btn btn-danger">Excluir</button></td>
    </tr>
  {% endfor %}

  </tbody>
</table>
{% endblock %}